# 时间日期格式化
spring:
  mvc:
    date-format: yyyy-MM-dd
    servlet:
      load-on-startup: 1

  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/themleaf?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456

mybatis:
  type-aliases-package: com.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
